// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package view_component_alert

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func alert() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return templ_7745c5c3_Err
	})
}

func AlertDeleteScript(href string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AlertDeleteScript_6ee4`,
		Function: `function __templ_AlertDeleteScript_6ee4(href){Swal.fire({
		title: 'Are you sure?',
		text: ` + "`" + `You won't be able to revert this!` + "`" + `,
		icon: 'warning',
		showCancelButton: true,
		confirmButtonColor: '#3085d6',
		cancelButtonColor: '#d33',
		confirmButtonText: 'Yes, delete it!'
	}).then((result) => {
		if (result.isConfirmed) {
			htmx.ajax('DELETE', href)
		}
	});
}`,
		Call:       templ.SafeScript(`__templ_AlertDeleteScript_6ee4`, href),
		CallInline: templ.SafeScriptInline(`__templ_AlertDeleteScript_6ee4`, href),
	}
}
