// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package view_component_alert

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func AlertDeleteScript(href string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_AlertDeleteScript_6ee4`,
		Function: `function __templ_AlertDeleteScript_6ee4(href){Swal.fire({
		title: 'Are you sure?',
		text: ` + "`" + `You won't be able to revert this!` + "`" + `,
		icon: 'warning',
		showCancelButton: true,
		confirmButtonColor: '#3085d6',
		cancelButtonColor: '#d33',
		confirmButtonText: 'Yes, delete it!'
	}).then((result) => {
		if (result.isConfirmed) {
			htmx.ajax('DELETE', href)
		}
	});
}`,
		Call:       templ.SafeScript(`__templ_AlertDeleteScript_6ee4`, href),
		CallInline: templ.SafeScriptInline(`__templ_AlertDeleteScript_6ee4`, href),
	}
}
