// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package view_admin_content_profile

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Profile(name, username, csrfToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"d-flex justify-content-center flex-column\"><div class=\"w-75 mx-auto\" x-data=\"{ edit: false }\"><h1 class=\"mb-3\">Profile</h1><div class=\"mb-3\" x-show=\"!edit\"><button class=\"btn btn-primary me-3\" @click=\"edit = true\">Edit</button></div><div class=\"mb-3\" x-show=\"edit\"><button hx-encoding=\"multipart/form-data\" hx-post=\"/user/profile\" hx-include=\"#edit-profile input\" hx-trigger=\"click\" class=\"btn btn-primary\">Save</button> <button class=\"btn btn-secondary\" @click=\"edit = false\">Cancel</button></div><div id=\"edit-profile\"><input type=\"text\" name=\"csrfToken\" class=\"d-none\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(csrfToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/admin/content/profile/profile.templ`, Line: 21, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div class=\"mb-3\"><label for=\"name\" class=\"form-label text-capitalize\">Name</label> <input type=\"text\" name=\"name\" class=\"form-control\" :disabled=\"!edit\" aria-label=\"disabled input name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/admin/content/profile/profile.templ`, Line: 24, Col: 120}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" id=\"name\" placeholder=\"your name\"></div><div class=\"mb-3\"><label for=\"username\" class=\"form-label\">Username</label> <input type=\"username\" name=\"username\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/admin/content/profile/profile.templ`, Line: 28, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" :disabled=\"!edit\" aria-label=\"disabled input name\" class=\"form-control\" id=\"username\" placeholder=\"your username\"></div><div x-show=\"edit\"><h3 class=\"mb-3\">Change Password</h3><div class=\"mb-3\"><label for=\"old_password\" class=\"form-label text-capitalize\">Old Password</label> <input type=\"password\" name=\"old_password\" class=\"form-control\" id=\"old_password\" placeholder=\"*****\"></div><div class=\"mb-3\"><label for=\"new_password\" class=\"form-label\">New Password</label> <input type=\"password\" name=\"new_password\" class=\"form-control\" id=\"new_password\" placeholder=\"*****\"></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
