// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package view_component_CKEeditor

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func showEditor(oldContents string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_showEditor_c9ba`,
		Function: `function __templ_showEditor_c9ba(oldContents){// let editor
    if(typeof ckeditor !== 'undefined') {    
        ckeditor
            .create( document.querySelector( '#editor' ))
            .then(newEditor => {
                newEditor.model.document.on( 'change', () => {
                    htmx.find("#res-content").value = newEditor.getData()
                } );
                window.editor = newEditor;
                editor.setData(oldContents)
            })
            .catch( error => {
                console.error( error );
            } );
    }else {
        window.addEventListener('load', function () {
            ckeditor
                .create( document.querySelector( '#editor' ))
                .then(newEditor => {
                    newEditor.model.document.on( 'change', () => {
                        htmx.find("#res-content").value = newEditor.getData()
                    } );
                    window.editor = newEditor;
                    editor.setData(oldContents)
                })
                .catch( error => {
                    console.error( error );
                } );
        })
    }
}`,
		Call:       templ.SafeScript(`__templ_showEditor_c9ba`, oldContents),
		CallInline: templ.SafeScriptInline(`__templ_showEditor_c9ba`, oldContents),
	}
}

func CKEeditor(oldContents string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\r\n        .ck-editor__editable_inline {\r\n            min-height: 300px;\r\n        }\r\n    </style><div id=\"editor\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = showEditor(oldContents).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
